CREATE TABLE PRODUCTOS3 (CODIGOARTICULO VARCHAR(4), SECCION VARCHAR(11), NOMBREARTICULO VARCHAR(20));

INSERT INTO PRODUCTOS3 (CODIGOARTICULO, SECCION, NOMBREARTICULO)
VALUES
("AR01","DEPORTES","RAQUETA"),
("AR02","FERRETERIA","TRINCHETA");
/*

CON UN ARCHIVO COMO ESTE LO IMPORTO DESDE PHPMYADMIN Y DIRECTAMENTE ME CREA
LA TABLA PRODUCTOS3 EN LA BBDD QUE ELEGI

*/